// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/category/:slug": {
    params: {
      "slug": string;
    };
  };
  "/category/:slug/question/:id": {
    params: {
      "slug": string;
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/leaderboard": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/category/:slug" | "/category/:slug/question/:id" | "/profile" | "/leaderboard" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/category.tsx": {
    id: "routes/category";
    page: "/category/:slug";
  };
  "routes/question.tsx": {
    id: "routes/question";
    page: "/category/:slug/question/:id";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/leaderboard.tsx": {
    id: "routes/leaderboard";
    page: "/leaderboard";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/home": typeof import("./src/app/routes/home.tsx");
  "routes/dashboard": typeof import("./src/app/routes/dashboard.tsx");
  "routes/category": typeof import("./src/app/routes/category.tsx");
  "routes/question": typeof import("./src/app/routes/question.tsx");
  "routes/profile": typeof import("./src/app/routes/profile.tsx");
  "routes/leaderboard": typeof import("./src/app/routes/leaderboard.tsx");
  "routes/not-found": typeof import("./src/app/routes/not-found.tsx");
};